# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: imageuploader

frameworkVersion: "2"

# The `provider` block defines where your service will be deployed
custom:
  bucket: getting-started-lambda-example
provider:
  name: aws
  region: eu-west-1
  stackName: imageuploader
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3.PutObject"
      Resource:
        - "arn:aws:s3:::${self:custom.bucket}/*"

# The `functions` block defines what code to deploy
functions:
  UploadImage:
    handler: uploadImage.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: upload
          method: post
          cors: true
    environment:
      Bucket: ${self:custom.bucket}
  resources:
    Resources:
      StorageBucket:
        Type: "AWS::S3::Bucket"
        Properties:
          BucketName: "bismillah-bisa"
